### ISSUE TITLE
Default to sane column widths in new errors dialog

### ISSUE THREAD

**Issue by csmith** [DMDirc/Plugins#281]
Severity really doesn't need to be 100px+ for a tiny little icon :)

![image](https://cloud.githubusercontent.com/assets/189133/5672153/165e4d3a-9786-11e4-9e40-f1e9819f5492.png)

**Comment by greboid** [comment]
I fixed the odd widths, but nearly all errors give overly long messages, will fix this with a tidy up of errors at some point, or some kind of auto trimming in the new DisplayableError at some point.

**Comment by greboid** [comment]
This needs addressing in another issue really.  Closing.
