### ISSUE TITLE
NickColours plugin no longer works for textpane

### ISSUE THREAD

**Issue by ShaneMcC** [DMDirc/Plugins#507]
Nicknames are no longer coloured in the text pane

**Comment by ShaneMcC** [comment]
(I assume this is new-formatter related, and that the {{client.nickname}} {{oldNick}} etc etc don't surround themselves with colour codes)

**Comment by ShaneMcC** [comment]
Similar to https://github.com/DMDirc/DMDirc/issues/424 I guess...

**Comment by ShaneMcC** [comment]
Would be nice to be able to suppress this in some places:

![formattercolourtimestamp](https://cloud.githubusercontent.com/assets/189723/21582270/66687aec-d048-11e6-9686-600c1584a93d.png)

(I don't want colours in the hostname, just the nicknames)

Also, it seems that this doesn't apply to all nicknames, eg {{oldNick}} in nick changes doesn't get a colour

**Comment by csmith** [comment]
I don't think there's any sane way to decide what gets arbitrarily coloured and what doesn't. A function to strip colours would probably work best?

Old nicknames are just strings, so don't have display properties. I guess we could wrap them in something, but it's a bit of work.

Can you raise separate issues for both? :)
